-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 15:10:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema linkedout
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema linkedout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `linkedout` DEFAULT CHARACTER SET utf8 ;
USE `linkedout` ;

-- -----------------------------------------------------
-- Table `linkedout`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`states` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`states` (
  `idstates` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`idstates`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`users` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `fname` VARCHAR(20) NOT NULL,
  `lname` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `city` VARCHAR(45) NULL,
  `state` INT NULL,
  `field` VARCHAR(45) NULL,
  `profile_views` INT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `state_idx` (`state` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `user_state`
    FOREIGN KEY (`state`)
    REFERENCES `linkedout`.`states` (`idstates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`work_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`work_experience` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`work_experience` (
  `user_id` INT NOT NULL,
  `experience_entry` INT NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`, `experience_entry`),
  CONSTRAINT `w_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`degree_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`degree_type` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`degree_type` (
  `deg_type_idx` INT NOT NULL AUTO_INCREMENT,
  `degree_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deg_type_idx`),
  UNIQUE INDEX `deg_type_idx_UNIQUE` (`deg_type_idx` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`major` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`major` (
  `major_idx` INT NOT NULL AUTO_INCREMENT,
  `major_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`education` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`education` (
  `user_id` INT NOT NULL,
  `education_entry` INT NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `deg_type_idx` INT NULL,
  `major_idx` INT NULL,
  `start_year` YEAR NULL,
  `end_year` YEAR NULL,
  PRIMARY KEY (`user_id`, `education_entry`),
  INDEX `deg_type_idx_idx` (`deg_type_idx` ASC),
  INDEX `major_idx_idx` (`major_idx` ASC),
  CONSTRAINT `ed_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `deg_type_idx`
    FOREIGN KEY (`deg_type_idx`)
    REFERENCES `linkedout`.`degree_type` (`deg_type_idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `major_idx`
    FOREIGN KEY (`major_idx`)
    REFERENCES `linkedout`.`major` (`major_idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`links` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`links` (
  `user_id` INT NOT NULL,
  `linked_user_id` INT NOT NULL,
  `linked_date` DATE NULL,
  PRIMARY KEY (`user_id`, `linked_user_id`),
  INDEX `linked_username_idx` (`linked_user_id` ASC),
  CONSTRAINT `user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `user2`
    FOREIGN KEY (`linked_user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`organizations` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`organizations` (
  `org_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `org_name` VARCHAR(45) NOT NULL,
  `org_description` VARCHAR(500) NULL,
  PRIMARY KEY (`org_id`),
  INDEX `org_admin_idx` (`user_id` ASC),
  CONSTRAINT `org_admin`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`users_orgs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`users_orgs` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`users_orgs` (
  `user_id` INT NOT NULL,
  `org_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `org_id`),
  INDEX `org_idx` (`org_id` ASC),
  CONSTRAINT `uo_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `uo_org`
    FOREIGN KEY (`org_id`)
    REFERENCES `linkedout`.`organizations` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`skills` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`skills` (
  `skills_id` INT NOT NULL AUTO_INCREMENT,
  `skill` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skills_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`user_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`user_skills` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`user_skills` (
  `user_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `skills_id`),
  INDEX `us_skill_idx` (`skills_id` ASC),
  CONSTRAINT `us_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `us_skill`
    FOREIGN KEY (`skills_id`)
    REFERENCES `linkedout`.`skills` (`skills_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`languages` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`languages` (
  `lang_id` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linkedout`.`user_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `linkedout`.`user_languages` ;

CREATE TABLE IF NOT EXISTS `linkedout`.`user_languages` (
  `user_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `lang_id`),
  INDEX `ul_lang_idx` (`lang_id` ASC),
  CONSTRAINT `ul_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `linkedout`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ul_lang`
    FOREIGN KEY (`lang_id`)
    REFERENCES `linkedout`.`languages` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `linkedout`.`states`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (1, 'Alabama');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (2, 'Alaska');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (3, 'Arizona');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (4, 'Arkansas');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (5, 'California');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (6, 'Colorado');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (7, 'Connecticut');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (8, 'Delaware');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (9, 'Florida');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (10, 'Georgia');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (11, 'Hawaii');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (12, 'Idaho');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (13, 'Illinois');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (14, 'Indiana');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (15, 'Iowa');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (16, 'Kansas');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (17, 'Kentucky');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (18, 'Louisiana');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (19, 'Maine');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (20, 'Maryland');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (21, 'Massachusetts');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (22, 'Michigan');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (23, 'Minnesota');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (24, 'Mississippi');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (25, 'Missouri');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (26, 'Montana');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (27, 'Nebraska');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (28, 'Nevada');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (29, 'New Hampshire');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (30, 'New Jersey');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (31, 'New Mexico');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (32, 'New York');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (33, 'North Carolina');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (34, 'North Dakota');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (35, 'Ohio');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (36, 'Oklahoma');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (37, 'Oregon');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (38, 'Pennsylvania');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (39, 'Rhode Island');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (40, 'South Carolina');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (41, 'South Dakota');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (42, 'Tennessee');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (43, 'Texas');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (44, 'Utah');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (45, 'Vermont');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (46, 'Virginia');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (47, 'Washington');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (48, 'West Virginia');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (49, 'Wisconsin');
INSERT INTO `linkedout`.`states` (`idstates`, `state`) VALUES (50, 'Wyoming');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`users` (`user_id`, `username`, `hashed_password`, `fname`, `lname`, `user_email`, `birthdate`, `city`, `state`, `field`, `profile_views`) VALUES (1, 'user', '$2y$10$oqkDqi7TY0ivbMAoJehnaOd3SfuzxMn1SL0sGKVkK3amSGXfJIG8m', 'John', 'Smith', 'j.smith@gmail.com', '1900-01-01', 'Columbia', 25, 'Computer Science', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`work_experience`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`work_experience` (`user_id`, `experience_entry`, `company`, `title`, `start_date`, `end_date`, `description`) VALUES (1, 1, 'Univesity of Missouri', 'User Support Analyst', '2014-01-01', NULL, 'Tech support');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`degree_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`degree_type` (`deg_type_idx`, `degree_type_name`) VALUES (1, 'Bachelor of Art');
INSERT INTO `linkedout`.`degree_type` (`deg_type_idx`, `degree_type_name`) VALUES (2, 'Bachelor of Science');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`major`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`major` (`major_idx`, `major_name`) VALUES (1, 'Computer Science');
INSERT INTO `linkedout`.`major` (`major_idx`, `major_name`) VALUES (2, 'Information Technology');
INSERT INTO `linkedout`.`major` (`major_idx`, `major_name`) VALUES (3, 'Business');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`education`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`education` (`user_id`, `education_entry`, `school`, `deg_type_idx`, `major_idx`, `start_year`, `end_year`) VALUES (1, 1, 'University of Missouri', 2, 1, 2013, 2017);

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`skills`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`skills` (`skills_id`, `skill`) VALUES (1, 'MS Office');
INSERT INTO `linkedout`.`skills` (`skills_id`, `skill`) VALUES (2, 'OS X');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`user_skills`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`user_skills` (`user_id`, `skills_id`) VALUES (1, 1);
INSERT INTO `linkedout`.`user_skills` (`user_id`, `skills_id`) VALUES (1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`languages`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`languages` (`lang_id`, `language`) VALUES (1, 'English');
INSERT INTO `linkedout`.`languages` (`lang_id`, `language`) VALUES (2, 'Spanish');
INSERT INTO `linkedout`.`languages` (`lang_id`, `language`) VALUES (3, 'French');
INSERT INTO `linkedout`.`languages` (`lang_id`, `language`) VALUES (4, 'German');

COMMIT;


-- -----------------------------------------------------
-- Data for table `linkedout`.`user_languages`
-- -----------------------------------------------------
START TRANSACTION;
USE `linkedout`;
INSERT INTO `linkedout`.`user_languages` (`user_id`, `lang_id`) VALUES (1, 1);
INSERT INTO `linkedout`.`user_languages` (`user_id`, `lang_id`) VALUES (1, 2);

COMMIT;

